# Generated by Django 4.0.6 on 2022-08-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MensajeriaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
