# Generated by Django 4.0.6 on 2022-08-02 16:28

import django.contrib.auth.base_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default=django.contrib.auth.base_user.AbstractBaseUser, max_length=150),
        ),
    ]
