# Generated by Django 4.0.6 on 2022-08-02 16:34

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=150),
        ),
    ]
