# Generated by Django 4.0.6 on 2022-08-29 20:42

import BlogApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blog', validators=[BlogApp.validators.validate_file_size], verbose_name=''),
        ),
    ]
