# Generated by Django 4.0.6 on 2022-08-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masdatosusuarios',
            name='avatar',
            field=models.ImageField(blank=True, default='LibreriaCoderApp\\static\\LibreriaCoderApp\x07ssets\\img\\AvatarPorDefecto.png', null=True, upload_to='avatares'),
        ),
    ]
