# Generated by Django 4.0.6 on 2022-08-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_masdatosusuarios_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masdatosusuarios',
            name='avatar',
            field=models.ImageField(blank=True, default='img/AvatarPorDefecto.png', null=True, upload_to='avatares'),
        ),
    ]
